enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Force hide player buttons background' 'Hide Shorts dimming' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide double tap to like animations' 'MaterialYou' 'Visual preferences icons'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom package name' 'Theme'"

[YouTube Music]
app-name = "YouTube Music"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"
included-patches = "'Hide double tap overlay filter' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom package name'"

[Meme Generator]
app-name = "Meme Generator"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free"

[Reddit]
app-name = "Reddit"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Tiktok]
app-name = "TikTok"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Twitch]
app-name = "Twitch"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
included-patches = "'Debug mode'"

[Twitter]
app-name = "Twitter"
build-mode = "both"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
included-patches = "'Hide FAB' 'Bring back twitter' 'Customize Navigation Bar items' 'Delete from database' 'Force enable translate' 'Hide promote button' 'Hide Community Notes' 'Hide Banner' 'Add ability to copy media link' 'Disable chirp font'"

[Yuka]
app-name = "Yuka"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan"
