enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
version = "auto"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube Music]
app-name = "YouTube Music"
version = "auto"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Meme Generator]
app-name = "Meme Generator"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free"
build-mode = "both"

[Reddit]
app-name = "Reddit"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
build-mode = "both"

[Tiktok]
app-name = "TikTok"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok"
build-mode = "both"

[Twitch]
app-name = "Twitch"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
build-mode = "both"

[Twitter]
app-name = "Twitter"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "both"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"

[Yuka]
app-name = "Yuka"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan"
build-mode = "both"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
